# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder ".", "/var/www/html/src"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "LAMP VM"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "Start Installing LAMP"
    sudo locale-gen UTF-8 > /dev/null
    sudo apt-get install -y language-pack-en-base > /dev/null
    sudo LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php -y > /dev/null
    sudo apt-get -y update > /dev/null

    echo "Installing Apache"
    sudo apt-get -y install apache2 > /dev/null

    echo "Installing PHP"
    sudo apt-get -y install php7.0 php7.0-mysql  > /dev/null # mod_php
    echo '<?php phpinfo(); ?>' | sudo tee --append /var/www/html/info.php  > /dev/null

    # sudo apt-get -y install curl git
    # curl --silent https://getcomposer.org/installer | php > /dev/null 2>&1
    # mv composer.phar /usr/local/bin/composer

    echo "Installing MySQL"
    DBPASSWD=abc123
    echo "mysql-server mysql-server/root_password password $DBPASSWD" | debconf-set-selections  > /dev/null
    echo "mysql-server mysql-server/root_password_again password $DBPASSWD" | debconf-set-selections  > /dev/null
    sudo apt-get -y install mysql-server  > /dev/null
    # sudo /usr/bin/mysql_secure_installation

    sudo service apache2 restart > /dev/null
    echo "Finish Installing LAMP!!!"
    
    echo "Open http://localhost:8080/info.php"

  SHELL
end
