# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "dhcpserver" do |dhcpserver|
    dhcpserver.vm.hostname = "dhcpserver"
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "public_network", ip: "192.168.0.17"
    config.vm.synced_folder "../../app/", "/var/www/html/src/"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "dhcpserver"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "Installing build essentials"
    sudo apt-get install -y build-essential

    echo "Start Installing LAMP"
    sudo locale-gen UTF-8 > /dev/null
    sudo apt-get install -y language-pack-en-base > /dev/null
    sudo LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php -y > /dev/null
    sudo apt-get -y update > /dev/null

    echo "Installing Apache"
    sudo apt-get -y install apache2 > /dev/null

    echo "Installing PHP"
    sudo apt-get -y install php7.0 php7.0-mysql  > /dev/null # mod_php
    echo '<?php phpinfo(); ?>' | sudo tee --append /var/www/html/info.php  > /dev/null

    sudo apt-get -y install curl git
    curl --silent https://getcomposer.org/installer | php > /dev/null 2>&1
    mv composer.phar /usr/local/bin/composer

    echo "Installing MySQL"
    DBPASSWD=abc123
    echo "mysql-server mysql-server/root_password password $DBPASSWD" | debconf-set-selections  > /dev/null
    echo "mysql-server mysql-server/root_password_again password $DBPASSWD" | debconf-set-selections  > /dev/null
    sudo apt-get -y install mysql-server  > /dev/null

    sudo service apache2 restart > /dev/null
    echo "Finish Installing LAMP!!!"

    echo "Importing database"
    mysql -u root --password="abc123" < /var/www/html/src/dhcpadmin/sql/ddl.sql

    sudo bash -c "echo 'www-data ALL=NOPASSWD: ALL' >> /etc/sudoers"

    echo "Installing DHCP Server"
    sudo apt-get -y install isc-dhcp-server

cat << EOF > /etc/default/isc-dhcp-server
INTERFACES="eth1"
EOF

cat << EOF > /etc/dhcp/dhcpd.conf
default-lease-time 600;
max-lease-time 7200;
authoritative;
option subnet-mask 255.255.255.0;
option broadcast-address 192.168.1.255;
option routers 192.168.1.254;
option domain-name-servers 192.168.1.1, 192.168.1.2;
option domain-name "mydomain.example";
subnet 192.168.0.0 netmask 255.255.255.0 {
    range 192.168.0.50 192.168.0.250;
}
EOF
    sudo service isc-dhcp-server start
    echo "Open http://localhost:8080/info.php"

  SHELL
  end

  config.vm.define "dhcpclient" do |dhcpclient|
    dhcpclient.vm.hostname = "dhcpclient"
    dhcpclient.vm.box = "ubuntu/trusty64"
    dhcpclient.vm.network "public_network", type: "dhcp"
    dhcpclient.vm.provider "virtualbox" do |vb|
      vb.name = "dhcpclient"
    end
    dhcpclient.vm.provision "shell", inline: <<-SHELL
    SHELL
  end
end
